name: comment-ops
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
concurrency:
  group: comment-ops-${{ github.event.issue.number }}
  cancel-in-progress: false
jobs:
  shipmate:
    name: shipmate
    uses: ship-iac/shipmate/.github/workflows/comment-ops.yml@9e126104de5c11495b08a9d4e324daa6ce293551 # v0.25.0
    permissions:
      contents: read
      issues: write
      pull-requests: write
      actions: read
    secrets:
      SHIPMATE_APP_PRIVATE_KEY: ${{ secrets.SHIPMATE_APP_PRIVATE_KEY }}
